POST http://localhost:3005/users HTTP/1.1
Content-type: application/json

{
    "first_name": "Seminar4",
    "last_name": "User",
    "email": "testing@email.com",
    "username": "rest-client-tester",
    "password": "testing123"
}

###